#!/bin/sh

set -e

LIMA_INSTANCE=$(basename $0)

case "$1" in
start)
	REALPATH=$0
	while [ -h "${REALPATH}" ]
	do
		REALPATH=$(readlink "${REALPATH}")
	done
	CFG=$(dirname "${REALPATH}")/${LIMA_INSTANCE}.yaml
	if ( limactl list | fgrep -q "${LIMA_INSTANCE}" )
	then
		limactl start "${LIMA_INSTANCE}"
	else
		limactl start "${CFG}" --tty=false
	fi
	docker context update ${LIMA_INSTANCE} --docker="host=tcp://localhost:2375" ||\
	docker context create ${LIMA_INSTANCE} --docker="host=tcp://localhost:2375"
	docker context use ${LIMA_INSTANCE}
	;;
stop)
	limactl stop ${LIMA_INSTANCE}
	;;
rm|remove)
	limactl remove ${LIMA_INSTANCE}
	;;
*)
	echo "Usage: $0 (start|stop|remove)"
	;;
esac
